### PR TITLE
Kaw 7686 carousel

### PR DESCRIPTION
**Pull request by TomaszDziezykNetcentric**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--edge-delivery-bimota--netcentric.hlx.page/
- After: https://kaw-7686-carousel--edge-delivery-bimota--netcentric.hlx.page/

### CODE REVIEW

**Review by lakshmishriaswathnarayana — CHANGES_REQUESTED** [review]
Everything looks good. Can you add this to sidekick ?

**Review by lakshmishriaswathnarayana — CHANGES_REQUESTED** [review]
Screenshot 2024-08-05 at 14 49 42

Slider Dots in this version should be inside the carousel can you handle that ?

**Comment by TomaszDziezykNetcentric** [comment]
> Screenshot 2024-08-05 at 14 49 42
> 
> Slider Dots in this version should be inside the carousel can you handle that ?

Done

**Comment by TomaszDziezykNetcentric** [comment]
> Everything looks good. Can you add this to sidekick ?

Added.
I added the configuration for the sidekick - it is already merged - so the library button should appear next to the preview button

**Review by lakshmishriaswathnarayana — APPROVED** [review]

**Pull request merged**
