### PR TITLE
Kaw 7947 specification

### PR DESCRIPTION
**Pull request by TomaszDziezykNetcentric**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #KAW-7947

Test URLs:
- Before: https://redesign-develop--edge-delivery-bimota--netcentric.hlx.page/drafts/tdziezyk/v2/specification
- After: https://KAW-7947-specification--edge-delivery-bimota--netcentric.hlx.page/drafts/tdziezyk/v2/specification

### CODE REVIEW

**Comment by IoanaOrca** [comment]
Screenshot 2024-10-07 at 13 48 20
The table int he test page is different form the design referring to the grey part and alignment. Was there an update?

**Comment by TomaszDziezykNetcentric** [comment]
> Screenshot 2024-10-07 at 13 48 20 The table int he test page is different form the design referring to the grey part and alignment. Was there an update?

It looks like something is not loaded. I'll need to check it

**Review by lakshmishriaswathnarayana — CHANGES_REQUESTED** [review]
There is more space compared to design between tables
Screenshot 2024-10-08 at 14 28 18

**Review by IoanaOrca — APPROVED** [review]

**Comment by TomaszDziezykNetcentric** [comment]
> There is more space compared to design between tables Screenshot 2024-10-08 at 14 28 18

Fixed

**Review by lakshmishriaswathnarayana — CHANGES_REQUESTED** [review]
Padding between button and text for greater than > XS is 60px.Can you handle that

**Comment by TomaszDziezykNetcentric** [comment]
> Padding between button and text for greater than > XS is 60px.Can you handle that

Fixed

**Review by lakshmishriaswathnarayana — APPROVED** [review]

**Pull request merged**
